### ISSUE TITLE
All Stock Size gas giants and stars still cannot be scaled correctly.

### ISSUE THREAD

**Issue by OrganicRigel** [SpaceNerd24/Celestial-Rescale#1]
You claim that the latest version has solved the problem of rescaling gas giants and stars, but according to my test (game version 1.12.5), in a typical 10.66x rescaling test (if it works properly, then Kerbin's size and mass are the same as the Earth in the real world, making it reasonable to explore the Stock System using Realism Overhaul), I found that the laythe, which is 10.66x in size, surrounds the Jool of Stock Size, and the entire Jool System is closer to Kerbol than Moho, while Kerbol becomes quite huge and looks like a red giant star, which makes it impossible for this system to explore properly. Therefore, we hope the bug can be fixed as soon as possible. When combined with Outer Planets Mod, the three additional giant planets sarnus, Urlum and Neidon cannot rescale properly, just like jool. All celestial bodies in the real solar system can achieve normal rescaling, but stars and gas giant in stock system such as Kerbol and Jool still cannot rescale properly.I don't know why Jupiter, Saturn, Uranus, and Neptune can get the correct rescaling, but Jool in the stock system and Sarnus, Ullum, and Neidon in OPM cannot get the correct rescaling.

**Comment by SpaceNerd24** [comment]
@OrganicRigel  could you send your log

**Comment by SpaceNerd24** [comment]
should be fixed in the next update
