### ISSUE TITLE
KSC is half in the ocean on 2.5x

### ISSUE THREAD

**Issue by ZWho1963** [SpaceNerd24/Celestial-Rescale#3]
This is a pretty good alternative to Rescale! and Sigma Dimensions, but there's just one gripe that I have: when booting up a 2.5x upscale of Kerbin, the KSC seems to be half in the ocean:
<img width="1440" alt="Screenshot 2024-10-25 at 9 12 23 pm" src="https://github.com/user-attachments/assets/011297ee-1990-48ee-8f29-aa98e9292945">

**Comment by SpaceNerd24** [comment]
This is a known issue and will be fixed in the next update, which should be done in a couple of weeks to a month.

**Comment by SpaceNerd24** [comment]
This Issue has been fixed and will be added in the next update.
